     <div class="jumbotron">
        <h3>DISCLAIMER / WEBSITEVOORWAARDEN</h3>
		<ol>
		<li>Op de inhoud en het gebruik van Opinie-over.nl zijn deze website- voorwaarden alsmede de huisregels van toepassing.</li>
		<li>Opinie-over.nl houdt zich het recht voor de op verstrekte informatie, onderhavige voorwaarden alsmede huisregels, geheel of gedeeltelijk aan te passen, te wijzigen en/of te vervangen. Alle wijzigingen van deze websitevoorwaarden zullen op deze pagina van de website worden geplaatst.</li>
		<li>De informatie op Opinie-over.nl is afkomstig uit openbare bronnen, van betrokken personen zelf, alsmede van derden, welke ieder voor zich voor de juistheid verantwoordelijk zijn.</li>
		<li>De informatie op Opinie-over.nl is bedoeld ter algemene informatie en oriëntatie. Vermenigvuldiging en verspreiding van de informatie is alleen toegestaan in ongewijzigde vorm en alleen voor niet-commercieel gebruik met vermelding van de bron en de naam Opinie-over.nl.</li>
		<li>Opinie-over.nl spant zich in de op haar website te verstrekken informatie zo volledig en nauwkeurig mogelijk samen te stellen en te onderhouden, maar staat niet in voor de juistheid, volledigheid en actualiteit daarvan.</li>
		<li>De informatie op Opinie-over.nl wordt aangeboden zonder enige garantie en Opinie-over.nl sluit elke aansprakelijkheid voor enig gebruik van de verstrekte informatie op Opinie-over.nl uit.</li>
		<li>Alle intellectuele (eigendoms)rechten (zoals auteursrechten, octrooien, merkrechten en databankrechten) met betrekking tot alle op deze website verstrekte informatie, databanken, afbeeldingen, koppelingen, teksten, bestanden, html-codes software, productnamen, bedrijfsnamen, merken, logo’s en handelsnamen (hierna aangeduid als “inhoud”) en de manier waarop de inhoud wordt gepubliceerd (met inbegrip van de vormgeving van Opinie-over.nl en overige visuele kenmerken) en alle informatie die daarmee verband houdt, behoren toe aan Opinie-over.nl of haar licentiegever(s). Op alle getoonde foto’s is copyright/portretrecht van toepassing. Het is verboden om foto’s van de site te gebruiken voor reproductie zonder voorafgaande schriftelijke toestemming.</li>
		<li>Opinie-over.nl garandeert niet dat de informatie altijd beschikbaar is en/of correct functioneert en dat Opinie-over.nl of de servers waarop de website beschikbaar wordt gesteld, vrij zijn van virussen of andere schadelijke elementen. Opinie-over.nl sluit elke hiermee verband houdende aansprakelijkheid in welke vorm dan ook, uit.</li>
		<li>Opinie-over.nl bevat links naar andere websites en/of servers die niet worden beheerd door Opinie-over.nl, zodat Opinie-over.nl op geen enkele wijze verantwoordelijk is voor de inhoud van dergelijke andere websites. Opinie-over.nl biedt dergelijke links slechts aan voor het gemak van de bezoekers van Opinie-over.nl en het opnemen ervan houdt geen aanbeveling in door Opinie-over.nl van de inhoud van dergelijke websites. Bezoekers dienen er rekening mee te houden dat andere websites en/of servers waarmee verbinding wordt gemaakt vanaf Opinie-over.nl, voorwaarden of bepalingen kunnen bevatten welke afwijken van onderhavige voorwaarden.</li>
		<li>Opinies, beweringen en/of meningen, geuit door of over de onderwerpen (personen of bedrijven) die door Opinie-over.nl zijn vermeld, zijn die van de auteur(s) en niet van Opinie-over.nl zélf. Voor de regels van publicatie wordt verwezen naar de van toepassing zijnde ‘huisregels’.</li>
		
		</ol>
      </div>